### ISSUE TITLE
请问IP记录和解析记录一致则放弃更改这个逻辑是什么意思呢？

### ISSUE THREAD

**Issue by liuyuanjun** [kkkgo/dnspod-ddns-with-bashshell#10]
> 使用API获取域名在Dnspod平台的ip记录，如果ip记录和本地解析记录或者外网解析记录相同则退出；

请问这个是为了处理什么呢？这样IP变化了就永远是旧的错的了吧？
有点困惑

**Comment by kkkgo** [comment]
你说的对，改错了。https://github.com/kkkgo/dnspod-ddns-with-bashshell/issues/9
