### ISSUE TITLE
可以添加ipv6吗

### ISSUE THREAD

**Issue by tt508618** [kkkgo/dnspod-ddns-with-bashshell#11]
ipv6已经普及了要是支持ipv6就太好了

**Comment by lgxnas** [comment]
好像只能使用修改记录接口
试了下update是不能访问的ipv4
我用的dnspod类似这样的
curl -s -X POST https://dnsapi.cn/Record.Modify -d login_token="${ID}','${TOKEN}"&format=json&domain="${DOMAIN}"&sub_domain="${SUBDOMAIN}&record_id="${RECORD_ID}"&record_type=AAAA&record_line_id=0&value="${LOCALIPV6}

**Comment by kkkgo** [comment]
这个项目是按IPV4设计的，IPV6要非常大的改动，后面计划单独做一个了。

**Comment by kkkgo** [comment]
现在已经支持IPV6啦~   
👉 https://github.com/kkkgo/UE-DDNS  

@tt508618 @lgxnas @zhpjy
