### ISSUE TITLE
API该换了，TTL设置有问题

### ISSUE THREAD

**Issue by PtO2** [kkkgo/dnspod-ddns-with-bashshell#15]
Record.Ddns这个接口没有TTL参数，会被设置成10，但实际最低只支持600，会导致解析失败。
要换成Record.Modify这个接口

**Comment by ghost** [comment]
> Record.Ddns这个接口没有TTL参数，会被设置成10，但实际最低只支持600，会导致解析失败。
> 要换成Record.Modify这个接口

兄弟能说下怎么改吗？我替换后报错

**Comment by jiehua233** [comment]
@stone-sir 
ddns="$(curl -4 -k $(if [ -n "$OUT" ]; then echo "--interface $OUT"; fi) -s -X POST https://dnsapi.cn/Record.Modify -d "${token}&record_id=${record_id}&record_line_id=${record_line_id}&record_type=AAAA&value=$DEVIP")"

**Comment by kkkgo** [comment]
根据最新官方文档，ttl为非必须项。
https://docs.dnspod.cn/api/update-dns-records/  
如果测试有报错希望反馈一下。
