### ISSUE TITLE
定时任务日志输出为空文件。。

### ISSUE THREAD

**Issue by 110560** [kkkgo/dnspod-ddns-with-bashshell#16]
手动执行命令 有日志输出
但是由于定时任务....定时任务运行 日志就会变成空文件。.....

直接执 bash /root/dnspod_ddns.sh &> /root/ddns.log 
能够看到日志有记录。

当定时任务开始运行
*/1 * * * * bash /root/dnspod_ddns.sh &> /root/ddns.log

ddns.log就是空文件。....

**Comment by jiehua233** [comment]
*/1 * * * * bash /root/dnspod_ddns.sh >> /root/ddns.log 2>&1
