### ISSUE TITLE
crontab无法使用

### ISSUE THREAD

**Issue by songzhishuo** [kkkgo/dnspod-ddns-with-bashshell#17]
我在crontab 中这样写：
*/1 * * * *  ~/dnspod-ddns-with-bashshell/dnspod_ddns.sh  >> /tmp/ddns 

但是输出的信息是：
Wed  9 Dec 16:26:01 GMT 2020
Get www.supermcu.xyz error :Operation successful

一直是error
求大佬能帮忙看看。

**Comment by WallBreakerNO4** [comment]
你这error出了个successful可还行

**Comment by songzhishuo** [comment]
> 你这error出了个successful可还行

就是这样啊，我还能骗你。。。。

**Comment by kkkgo** [comment]
尝试最新脚本。
