### ISSUE TITLE
支持ipv6

### ISSUE THREAD

**Issue by WangLeGeWang** [kkkgo/dnspod-ddns-with-bashshell#19]
可以支持ipv6吗？自带的ddns好像没有了ipv6的解析，arm版的群晖不好用docker

**Comment by kkkgo** [comment]
可以用新项目，支持IPv6:  https://github.com/kkkgo/UE-DDNS

**Comment by kkkgo** [comment]
这个项目是用脚本生成脚本，你可以群晖开ssh进入终端，运行向导，生成后的脚本可以用于群晖计划任务。

**Comment by WangLeGeWang** [comment]
> 这个项目是用脚本生成脚本，你可以群晖开ssh进入终端，运行向导，生成后的脚本可以用于群晖计划任务。

好的，谢谢了

**Comment by kkkgo** [comment]
另外群晖添加计划任务可以参考这个：  https://github.com/kkkgo/DSM_Login_BingWallpaper

**Comment by WangLeGeWang** [comment]
> 另外群晖添加计划任务可以参考这个： https://github.com/kkkgo/DSM_Login_BingWallpaper

我就是从这里翻到你的博客，然后才看到这个仓库的。23333
