### ISSUE TITLE
请问一下，脚本里面填写的邮箱地址是每次有ip更新都会发到这个邮箱吗？

### ISSUE THREAD

**Issue by SHEN-Cheng** [kkkgo/dnspod-ddns-with-bashshell#2]
如图，请教一下

**Comment by SHEN-Cheng** [comment]
![image](https://user-images.githubusercontent.com/40594953/47404336-7c3d2300-d77f-11e8-9379-1dc38ced019d.png)
下面会出现这个错误，不知道怎么弄

**Comment by kkkgo** [comment]
邮箱仅作为api文档的要求提交到api；
你这个错误看起来是api调用失败，你把第33行

> Record="$(curl $(if [ -n "$OUT" ]; then echo "--interface $OUT"; fi) -s -X POST https://dnsapi.cn/Record.List -d "${token}")"

改成
`curl -s -X POST https://dnsapi.cn/Record.List -d "${token}"`
然后运行看看有什么输出？
