### ISSUE TITLE
报错哦

### ISSUE THREAD

**Issue by keepeye** [kkkgo/dnspod-ddns-with-bashshell#3]
./dnspod_ddns.sh: 22: [: 0: unexpected operator
[DNS IP]:Get nas.yiika.com DNS Failed.
./dnspod_ddns.sh: 27: [: Get nas.****.com DNS Failed.: unexpected operator
./dnspod_ddns.sh: 36: [: 1: unexpected operator

**Comment by keepeye** [comment]
需要在脚本头部加 
#!/bin/bash

默认 sh 执行报错

**Comment by SHEN-Cheng** [comment]
Mon Oct 29 11:25:57 CST 2018
[URL IP]:114.****
[DNS IP]:58.*****
Get gaochun.***.club error :
出于隐私***的其实都已经解析出来了，但是出现最后一行这个error，不知道如何解决。
在脚本头部加了
#!/bin/bash
但是#的话不就是注释了没用了吗？

**Comment by kkkgo** [comment]
@keepeye 你用sh执行但你的shell脚本解释器是bash当然会报错，你加可执行权限直接执行就行，不用加sh。
@shen159876 你开的issue由于没回复所以关闭了，请按照[回复](https://github.com/lixuy/dnspod-ddns-with-bashshell/issues/2)的来测试。
