### ISSUE TITLE
TTL设置为10

### ISSUE THREAD

**Issue by DawnLiExp** [kkkgo/dnspod-ddns-with-bashshell#6]
更换ip成功后，发觉ttl会被设置成10，我是dnspod免费版用户(最小600)。

这算是免费用vip功能了，但我并不想设置那么低，😄️。

系统是自己最小化安装的debian 8.11，line和非line的都试过。

**Comment by kkkgo** [comment]
说出来你可能不信，这可能是dnspod的bug，然后官方的api文档已经三年没更新了，文档里在使用ddns的api更新dns记录的时候并没有ttl参数修改的功能，只有修改dns记录的api有修改ttl参数的功能，如果要加上修改ttl的功能估计要换普通的修改记录api重写并且未经测试（dnspod的bug太不稳定了，api文档中还要求电子邮箱的参数，但某天发现api莫名奇妙失效了，去掉电子邮箱反而能用，问官方也没说明），最后对于ddns来说，ttl越低越好应该没毛病，如果是bug的显示而实际上没有10，那没必要改，如果是真的10，那换常规的修改dns记录的api去操作达不到10的效果，综上，没必要修改。

**Comment by DawnLiExp** [comment]
好的，看来DNSPOD的API做的也不那么完善。10倒底是不是真的10也不大好测试，问题不大，并不是经常换。

感谢。
