### ISSUE TITLE
Get myDomain error :

### ISSUE THREAD

**Issue by 1368129224** [kkkgo/dnspod-ddns-with-bashshell#7]
![image](https://user-images.githubusercontent.com/20501378/51599885-a7c8d880-1f3b-11e9-9bca-f4222a17a06a.png)
按照[issue2](https://github.com/kkkgo/dnspod-ddns-with-bashshell/issues/2)的方法更改之后还是提示：Get myDomain error :
希望仔细指导一下，谢谢！

**Comment by kkkgo** [comment]
终端运行
curl -s -X POST https://dnsapi.cn/Record.List
看看有什么输出

**Comment by 1368129224** [comment]
> 终端运行
> curl -s -X POST https://dnsapi.cn/Record.List
> 看看有什么输出

![image](https://user-images.githubusercontent.com/20501378/51602248-781ccf00-1f41-11e9-8be7-b706d82ff1a8.png)

**Comment by kkkgo** [comment]
再尝试wget -S  https://dnsapi.cn/Record.List

**Comment by 1368129224** [comment]
> 再尝试wget -S https://dnsapi.cn/Record.List

执行`wget -S --no-check-certificate https://dnsapi.cn/Record.List`后保存了`Record.List`，内容如下：
```
<?xml version="1.0" encoding="UTF-8"?>
<dnspod>
<status>
<code>2</code>
<message>POST method accepted only</message>
<created_at>2019-01-23 19:11:52</created_at>
</status>
</dnspod>
```

**Comment by kkkgo** [comment]
再尝试执行curl https://baidu.com

**Comment by 1368129224** [comment]
> 再尝试执行curl https://baidu.com


![image](https://user-images.githubusercontent.com/20501378/51603682-748b4700-1f45-11e9-9c61-b2b2ff67e5bf.png)
路由器是K2P，固件是Powered by LuCI Master (git-18.346.39597-d1ebd59) / PandoraBox R8.1.12 By Lean，请问是不是固件的问题？

**Comment by kkkgo** [comment]
opkg update
opkg install ca-bundle ca-certificates

**Comment by 1368129224** [comment]
> opkg update
> opkg install ca-bundle ca-certificates

很难受，rom空间不足了，尝试卸载包报错：
```
Collected errors:
 * opkg_conf_write_status_files: Can't open status file //usr/lib/opkg/status: No space left on device.
```
我先自己研究一下，谢谢！

**Comment by kkkgo** [comment]
尝试新版本。https://github.com/kkkgo/dnspod-ddns-with-bashshell/commit/b1c36bae78ebca0c263da37cfc847605493f24eb

**Comment by kkkgo** [comment]
更新了脚本，如果有问题再回复，谢谢
