### ISSUE TITLE
大佬你的http://ip.03k.org 域名不稳定啊，经常获取ip  failed

### ISSUE THREAD

**Issue by mokitoo** [kkkgo/dnspod-ddns-with-bashshell#9]
大佬你的http://ip.03k.org 域名不稳定啊，经常获取ip  failed
然后脚本里面判断url ip 和 dns ip ， record ip 不等，就去dnspod更新，从而造成api被限制了。。。

**Comment by mokitoo** [comment]
按照现在的逻辑上来说，是不是Get  URLIP Failed 的时候，就不应该继续往下去执行了呢

**Comment by kkkgo** [comment]
测试暂时还没有获取不到的情况，你可以更换其他checkurl；
因为这脚本是cloudxns改过来的，刚刚已经加了dns和record一致就不更新；
脚本是尽力而为确保ip准确，所以failed还是会强制更新；
建议你可以减少脚本执行频率或者使用dnspod_ddns_line.sh。

**Comment by kkkgo** [comment]
另外dnspod的bug也很多，建议用cloudxns;
限制dns更新频率而对查询ip的频率却没有限制，实在是迷惑行为（所以添加了dns和record一致就不更新）

**Comment by mokitoo** [comment]
用dnspod的另一个尴尬的地方在于，一旦换到的新ip是个被墙的ip就麻烦了，请求dnspod的api直接被阻断了，应该说用国内的dns商家都会有这个问题

**Comment by kkkgo** [comment]
欢迎使用新脚本👉→ https://github.com/kkkgo/UE-DDNS
